Update python brasil 2023
pythonbrasil/manual pull request #27
Opened 2023-11-06 21:50 UTC by Perceu

- Adicionado links de eventos python brasil no historico
- Criado eventos até 2023 (sem dados ainda) 
- iniciado uma introdução de como organizar 
- Abrir discução nos topicos e compilar informações:

Discução na apyb
https://github.com/apyb/comunidade/discussions/10

Readthedocs desatualizado:
https://manual-do-big-kahuna.readthedocs.io/en/latest/

Documento para desenvolvimento de curso:
https://docs.google.com/document/d/1-4X0cyDUjYu3PdbS7sV7wZw97LmeaEPjNLufkborRG8/edit

2023-11-06 21:53 UTC, Perceu commented
Deixar aqui topico aberto em 2021 para compilar links os links 

https://github.com/pythonbrasil/pybr2021-org/issues/347

2023-11-06 22:20 UTC, Perceu commented
Guia desenvolvido pela apyb
https://apyb.python.org.br/guias/como-organizar-eventos/

2023-11-16 16:22 UTC, renan-assis-santos commented on source/organizacao/index.md
> +####  Time de Tecnico
Esse time ficou um pouco confuso pra mim quais as atribuições dele.
Cuidar das atualizações do site acho que poderia ser >> Criar o site do evento utilizando a URL que a Apyb disponibiliza (aquela 2022.pyhtonbrasil, 2023.pythonbrasil, etc) com base na identidade visual criada pelo time de design.
(outro topico sugerido pra adicionar) Manter o site atualizado com todas as informações que quisermos passar ao público (keynotes, plano de patrocinio, disponibilização da grade de palestras, local do evento, etc)

--
Cuidar dos acessos acho dificil centralizar em um time visto que tem um monte de sistema diferente e boa parte quem cuida é a apyb se n me engano.

--
Sistema de notificação n entendi.

2023-11-16 16:22 UTC, renan-assis-santos commented on source/organizacao/index.md
> +
Eu adicionaria um time de conteúdo ou qq outro nome relacionado. Aqui uma sugestão de responsabilidades

```suggestion
 #### Time de Conteúdo
 Responsável por gerenciar a grade de atividades oficiais do evento como palestras, tutoriais, assembleias, keynotes.
    - Criação e configuração do evento na ferramenta de submissão de atividades (por padrão utilizamos a ferramenta pretalx)
    - Criação do formulário de submissão de atividades considerando apenas aquelas que as pessoas possam vir a submeter.
    - Avaliação de atividades para definir quais entram na grade
    - Criação e configuração do evento na ferramenta de ingressos (por padrão utilizamos o eventbrite)
    - Porta-voz de relacionamento com os keynotes
```

2023-11-16 16:22 UTC, renan-assis-santos commented on source/organizacao/index.md
> + - Definir Identidade Visual com principais elementos e ja com mockups. Alguns mockups uteis:
Eu colocaria como primeiros itens e principais a criação do plano dde patrocinio ja com a identidade do evento e a criação do design do site, em terceiro os templates pra publicacao. O resto é menos prioritario, mas nao menos importante.

2023-11-16 16:22 UTC, renan-assis-santos commented on source/organizacao/index.md
> +   - o local para as palestras seria bom contemplar
**Necessário** contemplar tudo isso de baixo po kk.
Banheiros essencial, acessibilidade msm coisa pq vimos que pelo menos alguém cm pé quebrado sempre tem na pybr, sala pra org/keynotes a gente n vive sem, espaço pro coffe tbm mto importante.

2023-11-17 02:32 UTC, anadulce commented on source/organizacao/index.md
> +O time tecnico é de longe talvez o que mais pessoas va querer participar pois é um evento de tecnologia. Mas esse time tem a responsabilidade de:
Muito importante adicionar que o site da Python Brasil deve ser estático, independente de qual ferramenta queiram usar

2023-11-17 03:14 UTC, anadulce commented on source/organizacao/index.md
> +- Auxilio aos demais times.
Isso é uma coisa meio vaga, então não sei se vale a pena especificar

2023-11-17 03:17 UTC, anadulce commented on source/organizacao/index.md
> +- Criação do formulário de submissão de atividades considerando apenas aquelas que as pessoas possam vir a submeter.
Essa frase está um pouco confusa pra mim, poderia especificar melhor, por favor?

2023-11-17 03:18 UTC, anadulce commented on source/organizacao/index.md
> +- Criação e configuração do evento na ferramenta de ingressos (por padrão utilizamos o eventbrite)
Eu acho que isso são coisas diferentes, uma é ingresso outra é conteúdo

2023-11-17 03:28 UTC, anadulce commented on source/organizacao/index.md
> +- Porta-voz de relacionamento com os keynotes
Como keynotes tem toda uma logística, não acho que deveria estar com o time de conteúdo.
É muito rolê agendar viagem, reservar hospedagem.
Seria melhor ter uma pessoa só por conta disso (no máximo duas, não precisa ser um time)

2023-11-17 03:48 UTC, anadulce commented on source/organizacao/index.md
> +Atividades:
Pra mim essas atividades deveriam ter uma ordem de prioridade e falta uma definição básica do evento nesse roadmap.
Acho que a primeira coisa a ser feita a nível de gestão é definir seu objetivo. Um evento pra quantas pessoas? Mais ou menos em qual época? Dá tempo de organizar até essa data?
A partir disso, fechar o local do evento e datas.
É necessário um orçamento mínimo para ter ideia dos custos do evento e quanto será necessário para viabilizá-lo. Isso vai ajudar a definir as cotas de patrocínio e também os preços de ingressos.
Minha sugestão de orçamentos básicos é local do evento + coffee break + audiovisual, porque eles variam muito de cidade pra cidade, os demais podem ser estimados.
Definir o plano de patrocínio é a próxima coisa que precisa ser feita (você precisa das informações básicas de onde e quando pra isso) e captar recursos é a prioridade máxima enquanto o evento não se tornar viável.
Paralelamente, levar as outras iniciativas: ingressos, orçamentos, conteúdos.
Ter um cronograma de ingressos e conteúdos é extremamente útil, e um deadline para orçamentos.

2023-11-17 18:05 UTC, renan-assis-santos commented on source/organizacao/index.md
> +- Criação do formulário de submissão de atividades considerando apenas aquelas que as pessoas possam vir a submeter.
@anadulce essa fui eu que escrevi nas pressas hahaha eu quis dizer que era criar o formulario de submissao só pra palestras tutoriais e sprints pq no final a gente sempre adiciona um monte de tema no pretalx assembleia, keynote etc.
Mas da pra simplificar a frase pra:
- Criação do formulário de submissão de atividades na ferramenta escolhida

2023-11-17 18:08 UTC, renan-assis-santos commented on source/organizacao/index.md
> +- Criação e configuração do evento na ferramenta de ingressos (por padrão utilizamos o eventbrite)
Achei as informações mto boas, mas quis dizer um tópico ou um time separado pra cuidar de ingressos?

2023-11-17 18:08 UTC, renan-assis-santos commented on source/organizacao/index.md
> +- Porta-voz de relacionamento com os keynotes
Justo, mas ai seria bom colocar essa tarefa em algum dos outros times, tem alguma sugestao de qual?

2023-11-17 18:15 UTC, anadulce commented on source/organizacao/index.md
> +- Criação e configuração do evento na ferramenta de ingressos (por padrão utilizamos o eventbrite)
Ingressos pode ficar no time do financeiro, não faz sentido unir ingresso e conteúdo, porque são coisas completamente diferentes.
Como tem informações muito específicas, acho que valeria um tópico separado sim.

2023-11-17 18:21 UTC, anadulce commented on source/organizacao/index.md
> +- Porta-voz de relacionamento com os keynotes
Eu acho que essa tarefa está mais próxima do time de orçamentos do que conteúdos.

2023-11-17 18:26 UTC, anadulce commented on source/organizacao/index.md
> +- Criação e configuração do evento na ferramenta de ingressos (por padrão utilizamos o eventbrite)
Outro ponto válido aqui é deliberar sobre tópicos que sempre causam confusão: lembrar que a org é responsável por definir se pessoas que ministrarão conteúdos pagam ingressos e se organização paga ingresso, e que isso normalmente é definido com base nos orçamentos e arrecadação de patrocínios.

2023-11-17 19:05 UTC, renan-assis-santos commented on source/organizacao/index.md
> +- Criação e configuração do evento na ferramenta de ingressos (por padrão utilizamos o eventbrite)
Boa, acho válido ingressos entrar no time de financeiro com tópico separado com essas considerações que vc fez.

Mto boa a ideia de doação de grupos subrepresentados, acho que vale um sub topico do topico ingressos. Pq aqui não precisamos discutir como fazer e sim levantar a possibilidade de ser feita.

Nooossaa verdade, esse último tópico sempre gera treta. Colocar um subtopico dos ingressos de "Definir se org paga ingressos" e outro "Definir se palestrantes e ministrantes de tutoriais pagam ingressos (e deixar EXPLICITO no formulario de submissao de palestras)"

2023-11-17 19:06 UTC, renan-assis-santos commented on source/organizacao/index.md
> +- Porta-voz de relacionamento com os keynotes
Faz sentido, de todos acho que ta mais próximo de orçamentos msm.

2023-12-05 14:34 UTC, luzfcb commented
Dados das edições online de 2020, 2021 e 2022 estão em https://github.com/pythonbrasil/dados

2023-12-05 15:07 UTC, Perceu commented
> Dados das edições online de 2020, 2021 e 2022 estão em https://github.com/pythonbrasil/dados

Poderia me ajudar a compilar os dados ? pois ali estão os dados brutos, se conseguir compilar no formato abaixo eu me comprometo a atualizar aqui ou se puder abrir um PR com essa compilação te agradeço muito.

Nome Oficial: Python Brasil 2022
Local: Online            
Data:                            
Big Kahuna: 

Números
-------

Participantes
`````````````
Inscritos: #nº
Mulheres inscritas: #nº
Palestrantes: #nº
Palestrantes mulheres: #nº

Atividades
``````````
Palestras: #nº
Trilhas: #nº
Palestras Relâmpago: #nº
Tutoriais: #nº
Sprint: #S/N
Django Girls: #S/N

Financeiro
``````````

Receita Total:
Receita Inscrições:
Receita Patrocinadores:
Número de Patrocinadores:


Patrocinadores
``````````````
#patrocinio por categoria

**Voluntários**
#nome dos voluntarios

**Keynotes**
#nome dos keynotes

**Prêmio Dorneles Treméa & Jean Ferri**
#premiados

2023-12-05 16:27 UTC, renan-assis-santos approved these changes

2024-01-12 18:37 UTC, naanadr requested changes
Está ficando massa Perceu 😍

2024-01-12 18:37 UTC, naanadr commented on source/organizacao/index.md
> +# Tretas comuns:
Para manter o padrão de cabeçalho 😄 

```suggestion
# Tretas comuns
```

2024-01-12 18:37 UTC, naanadr commented on source/organizacao/index.md
> +# Tretas comuns:
Outro ponto, adiciona essa seção em um arquivo a parte. Acho que deixaria a usabilidade do site melhor, já que seria criado uma página nova com indices e tudo mais.

2024-01-12 18:37 UTC, naanadr commented on source/organizacao/index.md
> +Deve-se deixar isso explicito a todos, pois o evento não tem orçamento proprio ele deve ser sempre autocontido mesmo as camisetas da organização saem do custo do evento.
```suggestion
#### Os organizadores, palestrantes, ministrantes de tutorial, pagam ingresso?
---
Essa decisão é tomada pela organização. Dessa forma, todo ano é discutido esse tema para cada um desses grupos.

Levem em consideração os seguintes pontos:
 * Definam se organização paga ingresso e principalmente quem será considerado "organização". Uma opção é considerar que todas as pessoas que forem trabalhar no evento presencial não poderão aproveitá-lo, pois estarão ocupadas com as responsabilidades de org, então seria bom não pagarem.
 * Definam isso para palestrantes e ministrantes de tutoriais ANTES de abrir o Call For Papers para já deixar explicito na submissão.
 * Dependendo da situação econômica da região, do pais e da verba do evento, essa questão pode ser reconsiderada. 

> Deve-se deixar isso explicito a todos, pois o evento não tem orçamento proprio ele deve ser sempre autocontido mesmo as camisetas da organização saem do custo do evento.
```

2024-01-12 18:37 UTC, naanadr commented on source/organizacao/index.md
> +A comunidade se posiciona sempre e ajuda em outras situações, mas a organização do evento não pode se comprometer com isso.
```suggestion
####  Código de conduta (CDC)
---
O Comitê de Código de Conduta é organizado e montado com ajuda da organização, mas é totalmente independente tendo poder até em cima da organização durante a realização do evento. 

O CDC só cobre as atividades oficiais da Python Brasil (tutoriais, sprints, palestras, Django Girls), todos os demais eventos extraoficiais (Algorave, PyBar, Pós-Evento) pode causar situações para os próximos dias, mas o CDC não atua fora do evento (possíveis situações devem ser tratadas no evento). 

A comunidade se posiciona sempre e ajuda em outras situações, mas a organização do evento não pode se comprometer com isso.

> Importante destacar que é imprescindível, que toda a organização e comitê estejam a par do conteúdo do [Código de Conduta](https://python.org.br/cdc/).
```

2024-01-12 18:37 UTC, naanadr commented on source/organizacao/index.md
> +**OBS**: Cuidado para não abrir precedentes que possam exigir que toda a organização faça pois a comunidade gostou.
```suggestion
#### Programas de apoio de custo e ingressos cortesia para grupos sub-representados
---

Esse tipo de programa é sempre bem vindo, mas a organização deve sempre olhar para o financeiro e a viabilização do evento. 

A organização estando definida e organizada, pode-se ir atrás desses grupos e viabilizar a vinda deles através de iniciativas dos próprios grupos com o apoio da organização (apoiar na divulgação, alcance e suporte para viabilizar a parceria).

> A organização não deve se comprometer com a criação desses programas, pois é uma atividade da comunidade. A organização sempre é, e provavelmente sempre vai ser, sobrecarregada com outras atividades.

**OBS**: Cuidado para não abrir precedentes que possam exigir que toda a organização faça pois a comunidade gostou.
```

2024-01-12 18:37 UTC, naanadr commented on source/organizacao/index.md
> +Sugestão de trabalhos, as atividades e a ordem estão sempre em discussão e devem ser sempre atualizadas:
```suggestion
> Sugestão de trabalhos, as atividades e a ordem estão sempre em discussão e devem ser sempre atualizadas:
```

2024-01-12 18:37 UTC, naanadr commented on source/organizacao/index.md
> +  - Numero de locais (Muitas vezes não é possivel achar um espaço que contemple tutorias e palestras)
No site não foi suficiente essa quantidade de indentação.

![image](https://github.com/pythonbrasil/manual/assets/21251472/14abdc28-696a-4df4-980d-636b9986c546)

```suggestion
 - Definir tamanho do evento:
    - Numero de trilhas
    - Numero de pessoas
    - Numero de tutoriais
    - Numero de locais (Muitas vezes não é possivel achar um espaço que contemple tutorias e palestras)
```

2024-03-01 22:28 UTC, naanadr approved these changes

2024-03-01 22:28 UTC, merged